services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ..:/home/vscode/workspace
      - ~/.aws:/home/vscode/.aws
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
