# homebrew
brew "gcc"

# shell
brew "zsh"

# zsh plugin
brew "zsh-completions"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "fzf"

# util
brew "jq"

# git
brew "git"
brew "git-remote-codecommit"

# python
brew "uv"

# node.js
brew "volta"

# aws
brew "awscli"
brew "aws-cdk"

# docker
brew "docker"
