# homebrew
brew "gcc"

# shell
brew "zsh"

# zsh plugin
brew "zsh-completions"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

#util
brew "jq"

# pyton
# pyenv install command error
# brew "pyenv"
# brew "poetry"

#git
brew "git"
brew "git-remote-codecommit"

# Node.js
# brew "volta"
